CREATE SCHEMA cybershark;
---------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------
-- SAN_PHAM
CREATE TABLE SAN_PHAM(
	MA_SAN_PHAM		INT AUTO_INCREMENT NOT NULL,	
	TEN_SAN_PHAM	NVARCHAR(255) NOT NULL ,
    GIA_NHAP	FLOAT NOT NULL DEFAULT 0,
	MO_TA	VARCHAR(4096) ,
    TINH_TRANG BIT(1),
	SO_LUONG	INT NOT NULL DEFAULT 0,
	DON_GIA		FLOAT NOT NULL DEFAULT 0,
	MA_LOAI_SAN_PHAM	INT ,
	MA_THUONG_HIEU	INT ,
    MAIN_IMAGE	VARCHAR(255) NOT NULL,
    NGAY_TAO	DATETIME(6),
    NGAY_SUA	DATETIME(6),
    ENABLED	BIT(1) NOT NULL,
	CONSTRAINT PK_SP PRIMARY KEY(MA_SAN_PHAM)
);

------------------------------------------------------
-- HINH_ANH_SP
CREATE TABLE HINH_ANH_SP (
	MA_HINH_ANH	INT AUTO_INCREMENT NOT NULL,
    MA_SP	INT NOT NULL,
    HINH_ANH	VARCHAR(255) NOT NULL,
    CONSTRAINT PK_HA PRIMARY KEY(MA_HINH_ANH)
);

------------------------------------------------------
-- LOAI_SAN_PHAM
CREATE TABLE LOAI_SAN_PHAM(
	MA_LOAI_SAN_PHAM	INT AUTO_INCREMENT NOT NULL,
	TEN_LOAI_SAN_PHAM	NVARCHAR(255) NOT NULL UNIQUE,
    HINH_ANH	VARCHAR(255) NOT NULL,
    PARENT_ID INT,
    ALL_PARENT_IDS VARCHAR(256),
    ENABLED	BIT(1) NOT NULL,
	CONSTRAINT PK_LSP PRIMARY KEY(MA_LOAI_SAN_PHAM)
);

------------------------------------------------------
-- DISCOUNT
CREATE TABLE TIN_TUC(
	MA_TIN_TUC	INT AUTO_INCREMENT NOT NULL,
	TIEU_DE	NVARCHAR(100),
    MO_TA	TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci,
    HINH_ANH	VARCHAR(100),	
	NGAY_TAO	DATETIME ,
    NGAY_SUA	DATETIME ,
	CONSTRAINT PK_TIN_TUC PRIMARY KEY(MA_TIN_TUC)
);

-------------------------------------------------------
-- THUONG_HIEU
CREATE TABLE THUONG_HIEU(
	MA_THUONG_HIEU	INT AUTO_INCREMENT NOT NULL,
	TEN_THUONG_HIEU	NVARCHAR(255) NOT NULL,
    HINH_ANH	VARCHAR(128) NOT NULL,
	CONSTRAINT PK_THUONG_HIEU PRIMARY KEY(MA_THUONG_HIEU)
);

--------------------------------------------------------
-- QUAN_TRI_VIEN
CREATE TABLE QUAN_TRI_VIEN(
	MA_QUAN_TRI_VIEN	INT AUTO_INCREMENT NOT NULL,
	HO_QUAN_TRI_VIEN	NVARCHAR(45) NOT NULL,
	TEN_QUAN_TRI_VIEN	NVARCHAR(45) NOT NULL,
	DIA_CHI_EMAIL	VARCHAR(128) NOT NULL UNIQUE,
	MAT_KHAU	VARCHAR(64) NOT NULL,
    HINH_ANH	VARCHAR(64),
    ENABLED BIT(1) NOT NULL,
	CONSTRAINT PK_QTV PRIMARY KEY(MA_QUAN_TRI_VIEN)
);

----------------------------------------------------------
-- CHUC_DANH
CREATE TABLE CHUC_DANH(
	MA_CHUC_DANH	INT AUTO_INCREMENT NOT NULL,
    TEN_CHUC_DANH	NVARCHAR(50) NOT NULL,
    CONG_VIEC NVARCHAR(145) NOT NULL,
    CONSTRAINT PK_CD PRIMARY KEY(MA_CHUC_DANH)
);

----------------------------------------------------------
-- PHAN_QUYEN
CREATE TABLE PHAN_QUYEN(
	MA_QTV	INT NOT NULL,
    MA_CD	INT NOT NULL,
    CONSTRAINT PK_PQ PRIMARY KEY(MA_QTV, MA_CD)
);

----------------------------------------------------------
-- THANH_TOAN
CREATE TABLE THANH_TOAN(
	MA_THANH_TOAN	INT AUTO_INCREMENT NOT NULL,
	MA_KHACH_HANG	INT NOT NULL,
	LOAI_THANH_TOAN	NVARCHAR(50) NOT NULL,
	BEN_THU_BA	NVARCHAR(50),
	SO_TAI_KHOAN	CHAR(20),
	NGAY_HET_HAN	DATETIME,
	CONSTRAINT PK_TT PRIMARY KEY(MA_THANH_TOAN)
);

----------------------------------------------------------
-- KHACH_HANG
CREATE TABLE KHACH_HANG(
	MA_KHACH_HANG	INT AUTO_INCREMENT NOT NULL,
	DIA_CHI_EMAIL	VARCHAR(255) NOT NULL UNIQUE,
	MAT_KHAU	VARCHAR(64) NOT NULL,
	HO_KHACH_HANG	NVARCHAR(45) NOT NULL,
	TEN_KHACH_HANG	NVARCHAR(45) NOT NULL,
	SO_DIEN_THOAI	VARCHAR(15) NOT NULL,
	GIOI_TINH	NVARCHAR(6) NOT NULL,
	NGAY_SINH	DATETIME(6) NOT NULL,
	DIEM_TICH_LUY	INT NOT NULL DEFAULT 0,
	LOAI_KHACH_HANG	NVARCHAR(50) NOT NULL DEFAULT 'Khách hàng bình thường',
    ENABLED BIT(1) NOT NULL,
    NGAY_TAO DATETIME(6),
    DIA_CHI_1 VARCHAR(64) NOT NULL,
    DIA_CHI_2 VARCHAR(64),
    THANHPHO_TINH VARCHAR(45),
	CONSTRAINT PK_KH PRIMARY KEY(MA_KHACH_HANG)
);

------------------------------------------------------------
-- DIA_CHI
CREATE TABLE DIA_CHI(
	MA_DIA_CHI	INT AUTO_INCREMENT NOT NULL,
    MA_KHACH_HANG	INT NULL,
	DIA_CHI_1	NVARCHAR(64) NOT NULL,
    DIA_CHI_2	NVARCHAR(64),
	THANHPHO_TINH	NVARCHAR(45) NOT NULL,
    HO_NGUOI_NHAN	VARCHAR(45) NOT NULL,
    TEN_NGUOI_NHAN	VARCHAR(45) NOT NULL,
    SO_DIEN_THOAI	VARCHAR(15) NOT NULL,
	MAC_DINH	BIT(1) NOT NULL,
	CONSTRAINT PK_DIACHI PRIMARY KEY(MA_DIA_CHI)
);

-----------------------------------------------------------
-- GIO_HANG
CREATE TABLE GIO_HANG(
	MA_KHACH_HANG	INT NOT NULL,
    TONG_TIEN	FLOAT NOT NULL DEFAULT 0,
	CONSTRAINT PK_GIO_HANG PRIMARY KEY(MA_KHACH_HANG)
);

------------------------------------------------------------
-- CTGH
CREATE TABLE CTGH(
	MA_CTGH	INT AUTO_INCREMENT NOT NULL,
	MA_SP	INT NOT NULL,
    MA_KH	INT NULL,
	SO_LUONG	INT NOT NULL,
	CONSTRAINT PK_CTGH PRIMARY KEY(MA_CTGH)
);

------------------------------------------------------------
-- DON_HANG
CREATE TABLE DON_HANG(
	MA_DON_HANG	INT AUTO_INCREMENT NOT NULL,
	MA_THANH_TOAN	INT,
	MA_KHACH_HANG	INT NOT NULL,
	MA_DIA_CHI	INT,
	TRI_GIA	FLOAT NOT NULL DEFAULT 0,
	TINH_TRANG	NVARCHAR(50)  NOT NULL DEFAULT 'Chưa thanh toán',
    NGAY_TAO	DATETIME ,
    NGAY_SUA	DATETIME ,
	CONSTRAINT PK_DON_HANG PRIMARY KEY(MA_DON_HANG)
);

------------------------------------------------------------
-- VOUCHER
CREATE TABLE VOUCHER(
	MA_GIAM_GIA	VARCHAR(8) NOT NULL,
	TEN_MA_GIAM_GIA	NVARCHAR(255) NOT NULL,
	PHAN_TRAM_GIAM_GIA	FLOAT NOT NULL,
	NGAY_HET_HAN	DATETIME NOT NULL,
    NGAY_TAO	DATETIME ,
    NGAY_SUA	DATETIME ,
	CONSTRAINT PK_VOUCHER PRIMARY KEY(MA_GIAM_GIA)
);

------------------------------------------------------------
-- CTHD
CREATE TABLE CTDH(
	MA_DH	INT NOT NULL,
	MA_SP	INT NOT NULL,
	SO_LUONG	INT NOT NULL,
	CONSTRAINT PK_CTHD PRIMARY KEY(MA_DH, MA_SP)
);

------------------------------------------------------------
-- VOUCHER_DH
CREATE TABLE VOUCHER_DH(
	MA_DH INT NOT NULL,
	MA_VOUCHER VARCHAR(8) NOT NULL,
	CONSTRAINT PK_VOUCHER_DH PRIMARY KEY(MA_DH, MA_VOUCHER)
);

------------------------------------------------------------
-- PHAN_HOI
CREATE TABLE DANH_GIA(
	MA_DANH_GIA	INT AUTO_INCREMENT NOT NULL,
	MA_KHACH_HANG	INT NOT NULL,
	MA_SAN_PHAM	INT NOT NULL,
	DANH_GIA	FLOAT NOT NULL,
	BINH_LUAN	TEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci,
    NGAY_TAO	DATETIME ,
	CONSTRAINT PK_BINH_LUAN PRIMARY KEY(MA_DANH_GIA)
);

------------------------------------------------------------
-- Rang buoc constraint
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SL CHECK (SO_LUONG >= 0);
ALTER TABLE SAN_PHAM ADD CONSTRAINT CHK_SP_DONGIA CHECK (DON_GIA >= 0);
ALTER TABLE CTGH ADD CONSTRAINT CHK_CTGH_SL CHECK (SO_LUONG > 0);
ALTER TABLE DON_HANG ADD CONSTRAINT CHK_DH_TRIGIA CHECK (TRI_GIA >= 0);
ALTER TABLE DON_HANG ADD CONSTRAINT CHK_TINHTRANG CHECK (TINH_TRANG IN ('Chưa thanh toán','Đã thanh toán','Đang vận chuyển','Giao thành công','Hủy'));
ALTER TABLE VOUCHER ADD CONSTRAINT CHK_VOUCHER_PERCENT CHECK (PHAN_TRAM_GIAM_GIA BETWEEN 0.01 AND 0.99);
ALTER TABLE CTDH ADD CONSTRAINT CHK_CTHD_SL CHECK (SO_LUONG > 0);
ALTER TABLE KHACH_HANG ADD CONSTRAINT CHK_PHONE CHECK (SO_DIEN_THOAI NOT LIKE '%[^0-9]%');
ALTER TABLE KHACH_HANG ADD CONSTRAINT CHK_EMAIL CHECK (DIA_CHI_EMAIL LIKE '%_@__%.__%');
ALTER TABLE KHACH_HANG ADD CONSTRAINT CHK_DIEMTL CHECK (DIEM_TICH_LUY >= 0);
ALTER TABLE KHACH_HANG ADD CONSTRAINT CHK_TYPE CHECK (LOAI_KHACH_HANG IN ('Khách hàng bình thường','Khách hàng thân thiết','Khách hàng VIP'));
ALTER TABLE THANH_TOAN ADD CONSTRAINT CHK_LTT CHECK (LOAI_THANH_TOAN IN ('Thanh toán khi nhận hàng','Thanh toán trực tuyến'));
ALTER TABLE KHACH_HANG ADD CONSTRAINT CHK_KH_GEND CHECK ((GIOI_TINH = 'Nam') OR (GIOI_TINH = 'Nữ'));
ALTER TABLE DANH_GIA ADD CONSTRAINT CHK_DIEMDG CHECK (DANH_GIA BETWEEN 1 AND 5);

-------------------------------------------------------------
-- Khoa ngoai
-- SAN_PHAM
ALTER TABLE SAN_PHAM ADD CONSTRAINT FK01_SP FOREIGN KEY (MA_LOAI_SAN_PHAM) REFERENCES LOAI_SAN_PHAM(MA_LOAI_SAN_PHAM);
ALTER TABLE SAN_PHAM ADD CONSTRAINT FK02_SP FOREIGN KEY (MA_THUONG_HIEU) REFERENCES THUONG_HIEU(MA_THUONG_HIEU);

-- LOAI_SAN_PHAM
ALTER TABLE LOAI_SAN_PHAM ADD CONSTRAINT FK01_LSP FOREIGN KEY (PARENT_ID) REFERENCES LOAI_SAN_PHAM(MA_LOAI_SAN_PHAM);

-- HINH_ANH_SP
ALTER TABLE HINH_ANH_SP ADD CONSTRAINT FK01_HA FOREIGN KEY (MA_SP) REFERENCES SAN_PHAM(MA_SAN_PHAM);

-- PHAN_QUYEN
ALTER TABLE PHAN_QUYEN ADD CONSTRAINT FK01_PQ FOREIGN KEY (MA_QTV) REFERENCES QUAN_TRI_VIEN(MA_QUAN_TRI_VIEN);
ALTER TABLE PHAN_QUYEN ADD CONSTRAINT FK02_PQ FOREIGN KEY (MA_CD) REFERENCES CHUC_DANH(MA_CHUC_DANH);

-- THANH_TOAN
ALTER TABLE THANH_TOAN ADD CONSTRAINT FK01_TT FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG(MA_KHACH_HANG);

-- DIA_CHI
ALTER TABLE DIA_CHI ADD CONSTRAINT FK01_DC FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG(MA_KHACH_HANG);

-- GIO_HANG
ALTER TABLE GIO_HANG ADD CONSTRAINT FK01_GH FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG(MA_KHACH_HANG);

-- CTGH
ALTER TABLE CTGH ADD CONSTRAINT FK01_CTGH FOREIGN KEY (MA_KH) REFERENCES KHACH_HANG(MA_KHACH_HANG);
ALTER TABLE CTGH ADD CONSTRAINT FK02_CTGH FOREIGN KEY (MA_SP) REFERENCES SAN_PHAM(MA_SAN_PHAM);

-- DON_HANG
ALTER TABLE DON_HANG ADD CONSTRAINT FK01_DH FOREIGN KEY (MA_THANH_TOAN) REFERENCES THANH_TOAN(MA_THANH_TOAN);
ALTER TABLE DON_HANG ADD CONSTRAINT FK02_DH FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG(MA_KHACH_HANG);
ALTER TABLE DON_HANG ADD CONSTRAINT FK03_DH FOREIGN KEY (MA_DIA_CHI) REFERENCES DIA_CHI(MA_DIA_CHI);

-- CTDH
ALTER TABLE CTDH ADD CONSTRAINT FK01_CTDH FOREIGN KEY (MA_DH) REFERENCES DON_HANG(MA_DON_HANG);
ALTER TABLE CTDH ADD CONSTRAINT FK02_CTDH FOREIGN KEY (MA_SP) REFERENCES SAN_PHAM(MA_SAN_PHAM);

-- VOUCHER_DH
ALTER TABLE VOUCHER_DH ADD CONSTRAINT FK01_VOUCHER_DH FOREIGN KEY (MA_DH) REFERENCES DON_HANG(MA_DON_HANG);
ALTER TABLE VOUCHER_DH ADD CONSTRAINT FK02_VOUCHER_DH FOREIGN KEY (MA_VOUCHER) REFERENCES VOUCHER(MA_GIAM_GIA);

-- DANH_GIA
ALTER TABLE DANH_GIA ADD CONSTRAINT FK01_DG FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG(MA_KHACH_HANG);
ALTER TABLE DANH_GIA ADD CONSTRAINT FK02_DG FOREIGN KEY (MA_SAN_PHAM) REFERENCES SAN_PHAM(MA_SAN_PHAM);

DROP SCHEMA cybershark;